In [238]:
from coremltools.models.neural_network import datatypes, NeuralNetworkBuilder
from coremltools.models.utils import save_spec
import numpy as np
import coremltools as ct
from coremltools.models.neural_network.flexible_shape_utils import NeuralNetworkMultiArrayShape, NeuralNetworkMultiArrayShapeRange

In [285]:
dtype = 'float32'
input_dim = [1,1,1,4]

In [286]:
inputs = [('input1', datatypes.Array(*input_dim))]
inputs

[('input1', Array({1,1,1,4}))]

In [287]:
output = [('output', None)]

In [321]:
builder = NeuralNetworkBuilder(inputs, output, disable_rank5_shape_mapping=True)

In [322]:
input_ma_shape = builder.spec.description.input[0].type.multiArrayType

input_ma_shape.shapeRange.sizeRanges.add()
input_ma_shape.shapeRange.sizeRanges.add()
input_ma_shape.shapeRange.sizeRanges.add()
input_ma_shape.shapeRange.sizeRanges.add()


input_ma_shape.shapeRange.sizeRanges[0].lowerBound = 1
input_ma_shape.shapeRange.sizeRanges[0].upperBound = 1

input_ma_shape.shapeRange.sizeRanges[1].lowerBound = 1
input_ma_shape.shapeRange.sizeRanges[1].upperBound = 1

input_ma_shape.shapeRange.sizeRanges[2].lowerBound = 1
input_ma_shape.shapeRange.sizeRanges[2].upperBound = -1

input_ma_shape.shapeRange.sizeRanges[3].lowerBound = 1
input_ma_shape.shapeRange.sizeRanges[3].upperBound = -1

In [323]:
# output_ma_shape = builder.spec.description.output[0].type.multiArrayType

# output_ma_shape.shapeRange.sizeRanges.add()
# output_ma_shape.shapeRange.sizeRanges[0].lowerBound = 1
# output_ma_shape.shapeRange.sizeRanges[0].upperBound = -1

# output_ma_shape.shapeRange.sizeRanges.add()
# output_ma_shape.shapeRange.sizeRanges[1].lowerBound = 1
# output_ma_shape.shapeRange.sizeRanges[1].upperBound = -1

In [324]:

# builder.add_argmax(name='argmax', input_name='input1', output_name='output', axis=3)

# builder.add_reshape_dynamic(name ='reshape', input_names=['input1'], output_name='output')
builder.add_squeeze('squeeze', input_name='input1', output_name='output', squeeze_all=True)
# builder.add_reshape_static(name ='reshape', input_name='input1',output_name='output', output_shape= (2,2))

name: "squeeze"
input: "input1"
output: "output"
squeeze {
  squeezeAll: true
}

In [325]:
model = ct.models.MLModel(builder.spec)

In [326]:
print(model)

input {
  name: "input1"
  type {
    multiArrayType {
      shape: 1
      shape: 1
      shape: 1
      shape: 4
      dataType: DOUBLE
      shapeRange {
        sizeRanges {
          lowerBound: 1
          upperBound: 1
        }
        sizeRanges {
          lowerBound: 1
          upperBound: 1
        }
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
        sizeRanges {
          lowerBound: 1
          upperBound: -1
        }
      }
    }
  }
}
output {
  name: "output"
  type {
    multiArrayType {
      dataType: DOUBLE
    }
  }
}



In [327]:
test_arr = np.arange(8).reshape(1,1,2,4).astype(dtype)
print(test_arr.shape)
print('---------------')
print(test_arr)

(1, 1, 2, 4)
---------------
[[[[0. 1. 2. 3.]
   [4. 5. 6. 7.]]]]


In [328]:
pred = model.predict(data={'input1': test_arr})['output']
# output = np.array(output)
print(pred.shape)
print('---------------')
print(pred)

(2, 4)
---------------
[[0. 1. 2. 3.]
 [4. 5. 6. 7.]]


In [271]:
input_dim= 4

In [180]:
a_np1 = np.arange(input_dim).astype(dtype)
a_np1

array([0., 1., 2., 3.], dtype=float32)

In [125]:
a_np2 = np.arange(input_dim).astype(dtype)
a_np2

array([0., 1., 2., 3.], dtype=float32)

In [126]:
b_np = np.add(a_np1, a_np2) + 2
b_np

array([2., 4., 6., 8.], dtype=float32)