In [1]:
import numpy as np

- lets replicate the yolo predictions
- grid = 2,2
- each grid will have 3 boxes
- there will be 3 classes


In [52]:
GRID_SIZE = 3
num_classes = 2
BOXES_PER_CELL = 3
# x,y,w,h,o,c1.c2.....,cn (5+CLASSES_NUM)

In [46]:
total_ele = ((5 + num_classes) * ANCHORS_NUM) * GRID_SIZE * GRID_SIZE
raw_preds = np.arange(total_ele).reshape(1, (5 + num_classes) * BOXES_PER_CELL , GRID_SIZE, GRID_SIZE)
print(raw_preds.shape) 
print(raw_preds) 

(1, 21, 2, 2)
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]

  [[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]

  [[36 37]
   [38 39]]

  [[40 41]
   [42 43]]

  [[44 45]
   [46 47]]

  [[48 49]
   [50 51]]

  [[52 53]
   [54 55]]

  [[56 57]
   [58 59]]

  [[60 61]
   [62 63]]

  [[64 65]
   [66 67]]

  [[68 69]
   [70 71]]

  [[72 73]
   [74 75]]

  [[76 77]
   [78 79]]

  [[80 81]
   [82 83]]]]


In [47]:
raw_preds = np.transpose(raw_preds, (0, 2, 3, 1))
print(raw_preds.shape) 
print(raw_preds) 

(1, 2, 2, 21)
[[[[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80]
   [ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81]]

  [[ 2  6 10 14 18 22 26 30 34 38 42 46 50 54 58 62 66 70 74 78 82]
   [ 3  7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67 71 75 79 83]]]]


In [48]:
raw_preds = raw_preds.reshape((1, GRID_SIZE**2, BOXES_PER_CELL, num_classes + 5))
print(raw_preds.shape) 
print(raw_preds) 

(1, 4, 3, 7)
[[[[ 0  4  8 12 16 20 24]
   [28 32 36 40 44 48 52]
   [56 60 64 68 72 76 80]]

  [[ 1  5  9 13 17 21 25]
   [29 33 37 41 45 49 53]
   [57 61 65 69 73 77 81]]

  [[ 2  6 10 14 18 22 26]
   [30 34 38 42 46 50 54]
   [58 62 66 70 74 78 82]]

  [[ 3  7 11 15 19 23 27]
   [31 35 39 43 47 51 55]
   [59 63 67 71 75 79 83]]]]


In [49]:
tx = raw_preds[:,:,:,0]
tx

array([[[ 0, 28, 56],
        [ 1, 29, 57],
        [ 2, 30, 58],
        [ 3, 31, 59]]])

In [38]:
ty = raw_preds[:,:,:,1]
ty

array([[[ 4, 32, 60],
        [ 5, 33, 61],
        [ 6, 34, 62],
        [ 7, 35, 63]]])

In [68]:
CX = np.tile(np.arange(GRID_SIZE), GRID_SIZE)
print(CX)
print('------------------')
CX = CX.reshape(1, GRID_SIZE**2, 1)
print(CX)

[0 1 2 0 1 2 0 1 2]
------------------
[[[0]
  [1]
  [2]
  [0]
  [1]
  [2]
  [0]
  [1]
  [2]]]


In [72]:
CY = np.tile(np.arange(GRID_SIZE), GRID_SIZE)
print(CY)
print('--------CY.reshape(1, GRID_SIZE, GRID_SIZE)----------')
CY = CY.reshape(1, GRID_SIZE, GRID_SIZE)
print(f'crrent shape {CY.shape}')
print(CY)
print('--------CY = CY.T----------')
CY = CY.T
print(f'transposed shape {CY.shape}')
print(CY)
print('---------CY = CY.reshape(1, GRID_SIZE**2, 1)---------')
CY = CY.reshape(1, GRID_SIZE**2, 1)
print(CY)
print('------------------')

[0 1 2 0 1 2 0 1 2]
--------CY.reshape(1, GRID_SIZE, GRID_SIZE)----------
crrent shape (1, 3, 3)
[[[0 1 2]
  [0 1 2]
  [0 1 2]]]
--------CY = CY.T----------
transposed shape (3, 3, 1)
[[[0]
  [0]
  [0]]

 [[1]
  [1]
  [1]]

 [[2]
  [2]
  [2]]]
---------CY = CY.reshape(1, GRID_SIZE**2, 1)---------
[[[0]
  [0]
  [0]
  [1]
  [1]
  [1]
  [2]
  [2]
  [2]]]
------------------


In [66]:
test_arr = np.arange(12).reshape(2,2,3)
print(test_arr.shape) 
print(test_arr)
test_arr = test_arr.reshape(-1)
print('------------ after reshape')
print(test_arr.shape) 
print(test_arr)

(2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
------------ after reshape
(12,)
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
test_arr